language: node_js
install:
  - npm install
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - "$HOME/.npm"
jobs:
  include:
    - stage: Test
      script:
        - npm test
